//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string direccion_notificacion { get; set; }
        public decimal maximo_procesos { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public string columna_abogado { get; set; }
        public Nullable<decimal> nivel { get; set; }
        public string columna_busqueda { get; set; }
        public int maximo_usuarios { get; set; }
        public bool activo { get; set; }
        public decimal maximo_espacio_disco { get; set; }
        public System.Guid license_key { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string logo { get; set; }
        public int VJConnectMaximoProcesos { get; set; }
        public string RepositorioDocumentos { get; set; }
        public int PaisId { get; set; }
        public int CodigoAlternoConsecutivo { get; set; }
        public int TipoLicenciaId { get; set; }
    }
}
