//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class actuaciones_judiciales
    {
        public decimal item { get; set; }
        public string codigo_cliente { get; set; }
        public decimal obligacion { get; set; }
        public string codigo_actuacion { get; set; }
        public Nullable<decimal> actuacion_padre { get; set; }
        public System.DateTime fecha_actuacion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string observacion { get; set; }
        public string usuario_insercion { get; set; }
        public Nullable<System.DateTime> fecha_insercion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string aprobado { get; set; }
        public string aprobado_por { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public string clase_actuacion { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> tipo_actuacion { get; set; }
        public Nullable<int> tipo_etapa { get; set; }
        public string hora_actuacion { get; set; }
        public string hora_vencimiento { get; set; }
        public Nullable<int> ejecutado { get; set; }
        public Nullable<int> responsable { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
