//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria_usuarios
    {
        public decimal item { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string codigo_cliente { get; set; }
        public string codugo_usuario { get; set; }
        public string codigo_accion { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public decimal obligacion { get; set; }
        public string ip { get; set; }
    }
}
