//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaDS
    {
        public int IdRegistro { get; set; }
        public int IdProceso { get; set; }
        public int IdEvento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ValorInt { get; set; }
        public string ValorString { get; set; }
        public Nullable<double> TiempoEspera { get; set; }
        public Nullable<System.DateTime> FechaHoraNew { get; set; }
    }
}
