//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos_cuentas
    {
        public string id_cuenta { get; set; }
        public int id_grupo { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual grupos grupos { get; set; }
    }
}
