//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTTP500Errors
    {
        public int Id { get; set; }
        public System.DateTime Dt { get; set; }
        public string Url { get; set; }
        public string AspDesc { get; set; }
        public string AspNumber { get; set; }
        public int AspLine { get; set; }
        public int AspColumn { get; set; }
        public string ErrDesc { get; set; }
        public string ErrNumber { get; set; }
        public string Ref { get; set; }
        public string Ip { get; set; }
        public string Ua { get; set; }
        public string Method { get; set; }
        public string Data { get; set; }
        public string id_cuenta { get; set; }
        public Nullable<int> id_usuario { get; set; }
    }
}
