//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public procesos()
        {
            this.ProcesosDS = new HashSet<ProcesosDS>();
            this.ProcesosTYBA = new HashSet<ProcesosTYBA>();
        }
    
        public string codigo_cliente { get; set; }
        public decimal obligacion { get; set; }
        public Nullable<int> clase_proceso { get; set; }
        public string demandante { get; set; }
        public string id_demandante { get; set; }
        public string demandado { get; set; }
        public string id_demandado { get; set; }
        public Nullable<int> tipo_intervencion { get; set; }
        public Nullable<int> intervencion_tercero { get; set; }
        public Nullable<decimal> tercero { get; set; }
        public string id_tercero { get; set; }
        public string actor { get; set; }
        public Nullable<int> regional { get; set; }
        public string ubicacion_fisica { get; set; }
        public string abogado { get; set; }
        public string abogado2 { get; set; }
        public string socio { get; set; }
        public string corresponsal { get; set; }
        public string dependiente { get; set; }
        public Nullable<int> tipo_tema { get; set; }
        public Nullable<int> tipo_estado { get; set; }
        public string abogado_contraparte { get; set; }
        public decimal pretension { get; set; }
        public Nullable<int> tipo_juzgado { get; set; }
        public Nullable<int> numero_juzgado { get; set; }
        public Nullable<int> ciudad_juzgado { get; set; }
        public Nullable<int> tipo_juzgado_origen { get; set; }
        public Nullable<int> numero_juzgado_origen { get; set; }
        public Nullable<int> ciudad_juzgado_origen { get; set; }
        public string radicacion { get; set; }
        public string funcionario { get; set; }
        public string instancia { get; set; }
        public Nullable<System.DateTime> fecha_digitacion { get; set; }
        public Nullable<System.DateTime> fecha_presentacion_demanda { get; set; }
        public Nullable<System.DateTime> fecha_admision_demanda { get; set; }
        public Nullable<System.DateTime> fecha_notificacion_demanda { get; set; }
        public Nullable<System.DateTime> fecha_llamamiento { get; set; }
        public Nullable<System.DateTime> fecha_entrega_abogado { get; set; }
        public Nullable<System.DateTime> fecha_sentencia { get; set; }
        public Nullable<System.DateTime> fecha_archivo { get; set; }
        public string hechos { get; set; }
        public string pretensiones { get; set; }
        public string calificacion_motivos { get; set; }
        public string calificacion_clase { get; set; }
        public Nullable<decimal> monto_provision { get; set; }
        public Nullable<decimal> valor_asegurado { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> etapa { get; set; }
        public Nullable<decimal> porcentaje_recuperacion { get; set; }
        public Nullable<int> tipo_dependencia { get; set; }
        public string observacion_abogado { get; set; }
        public Nullable<System.DateTime> fecha_observacion_abogado { get; set; }
        public string proceso_vigilado { get; set; }
        public string columna_busqueda { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> ultima_actuacion { get; set; }
        public string referencia { get; set; }
        public Nullable<int> id_abogado { get; set; }
        public Nullable<int> usuario_insercion { get; set; }
        public Nullable<int> tipo_sentencia { get; set; }
        public string paz_y_salvo_abogado { get; set; }
        public string codigo_alterno { get; set; }
        public Nullable<int> UltimaActuacionDS { get; set; }
        public Nullable<System.DateTime> fecha_sentencia_segunda_instancia { get; set; }
        public Nullable<int> tipo_sentencia_segunda_instancia { get; set; }
        public string sentido_sentencia { get; set; }
        public string sentido_sentencia_segunda_instancia { get; set; }
        public Nullable<System.DateTime> fecha_recepcion_proceso { get; set; }
        public string LoteNumero { get; set; }
        public Nullable<int> id_area { get; set; }
        public string RadicacionOrigen { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual tipo_estados tipo_estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesosDS> ProcesosDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesosTYBA> ProcesosTYBA { get; set; }
    }
}
