//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int ProductoId { get; set; }
        public string CodigoProducto { get; set; }
        public string Linea { get; set; }
        public string NombreProducto { get; set; }
        public string UnidadMedida { get; set; }
        public decimal ValorUnitario { get; set; }
        public decimal Iva { get; set; }
        public string Total { get; set; }
    }
}
