//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_estados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_estados()
        {
            this.procesos = new HashSet<procesos>();
        }
    
        public int tipo_estado { get; set; }
        public string nombre { get; set; }
        public string proceso_vigente { get; set; }
        public string id_cuenta { get; set; }
        public bool eliminado { get; set; }
        public string terminacion_anormal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesos> procesos { get; set; }
    }
}
