//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokens
    {
        public decimal id_token { get; set; }
        public System.Guid token { get; set; }
        public int id_usuario { get; set; }
        public string id_cuenta { get; set; }
        public System.DateTime fecha_hora { get; set; }
    }
}
