//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.grupos = new HashSet<grupos>();
        }
    
        public int id_usuario { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string cargo { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string pwd { get; set; }
        public string activo { get; set; }
        public int zona_horaria_diferencia { get; set; }
        public bool eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupos> grupos { get; set; }
    }
}
