//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedelexDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_usuarios_cuentas
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string cargo { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string pwd { get; set; }
        public string nombre_cliente { get; set; }
        public string direccion_notificacion { get; set; }
        public Nullable<decimal> maximo_procesos { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public string columna_busqueda { get; set; }
        public string activo { get; set; }
        public string tipo_sitio { get; set; }
        public string nomestado { get; set; }
        public int id_usuario { get; set; }
        public string id_cuenta { get; set; }
        public bool eliminado { get; set; }
        public string RepositorioDocumentos { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<int> CodigoAlternoConsecutivo { get; set; }
        public Nullable<bool> ClienteActivo { get; set; }
    }
}
